Repository UMC-CUK-8th/Android, pull requests merged in 2025-05, with the labels that each got.

#26 5주차미션_민트
  Mint/Flo/app/build.gradle.kts
  Mint/Flo/app/src/main/AndroidManifest.xml
  Mint/Flo/app/src/main/java/com/flow/MainActivity.kt
  Mint/Flo/app/src/main/java/com/flow/MusicService.kt
  Mint/Flo/app/src/main/java/com/flow/SongActivity.kt
  Mint/Flo/app/src/main/res/layout/activity_main.xml
  Mint/Flo/app/src/main/res/layout/activity_song.xml
Labels: feat

#31 6주차미션_잭
  Jack/Jack_Week4/.gradle/8.11.1/executionHistory/executionHistory.bin
  Jack/Jack_Week4/.gradle/8.11.1/executionHistory/executionHistory.lock
  Jack/Jack_Week4/.gradle/8.11.1/fileHashes/fileHashes.bin
  Jack/Jack_Week4/.gradle/8.11.1/fileHashes/fileHashes.lock
  Jack/Jack_Week4/.gradle/8.11.1/fileHashes/resourceHashesCache.bin
  Jack/Jack_Week4/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  Jack/Jack_Week4/.kotlin/errors/errors-1746508758003.log
  Jack/Jack_Week4/.kotlin/errors/errors-1746589845857.log
  Jack/Jack_Week4/app/src/main/java/com/example/jack_week4/Album.kt
  Jack/Jack_Week4/app/src/main/java/com/example/jack_week4/AlbumAdapter.kt
  Jack/Jack_Week4/app/src/main/java/com/example/jack_week4/AlbumFragment.kt
  Jack/Jack_Week4/app/src/main/java/com/example/jack_week4/AlbumRVAdapter.kt
  Jack/Jack_Week4/app/src/main/java/com/example/jack_week4/HomeFragment.kt
  Jack/Jack_Week4/app/src/main/java/com/example/jack_week4/LibraryFragment.kt
  Jack/Jack_Week4/app/src/main/java/com/example/jack_week4/LibraryVPAdapter.kt
  Jack/Jack_Week4/app/src/main/java/com/example/jack_week4/MainActivity.kt
  Jack/Jack_Week4/app/src/main/java/com/example/jack_week4/MusicFileFragment.kt
  Jack/Jack_Week4/app/src/main/java/com/example/jack_week4/SavedAlbumFragment.kt
  Jack/Jack_Week4/app/src/main/java/com/example/jack_week4/SavedSongFragment.kt
  Jack/Jack_Week4/app/src/main/java/com/example/jack_week4/SavedSongRVAdapter.kt
  Jack/Jack_Week4/app/src/main/java/com/example/jack_week4/Song.kt
  Jack/Jack_Week4/app/src/main/java/com/example/jack_week4/SongActivity.kt
  Jack/Jack_Week4/app/src/main/java/com/example/jack_week4/SongAdapter.kt
  Jack/Jack_Week4/app/src/main/res/drawable/ic_my_like_on.png
  Jack/Jack_Week4/app/src/main/res/layout/fragment_home.xml
  Jack/Jack_Week4/app/src/main/res/layout/fragment_library.xml
  Jack/Jack_Week4/app/src/main/res/layout/fragment_library_musicfile.xml
  Jack/Jack_Week4/app/src/main/res/layout/fragment_library_savedalbum.xml
  Jack/Jack_Week4/app/src/main/res/layout/fragment_library_savedsong.xml
  Jack/Jack_Week4/app/src/main/res/layout/fragment_saved_album.xml
  Jack/Jack_Week4/app/src/main/res/layout/fragment_saved_song.xml
  Jack/Jack_Week4/app/src/main/res/layout/fragment_song.xml
  Jack/Jack_Week4/app/src/main/res/layout/item_album.xml
  Jack/Jack_Week4/app/src/main/res/layout/item_library_album.xml
  Jack/Jack_Week4/app/src/main/res/layout/item_song.xml
  Jack/Jack_Week4/app/src/main/res/values/colors.xml
Labels: style

#29 6주차미션_민트
  Mint/Flo/app/src/main/java/com/flow/MainActivity.kt
  Mint/Flo/app/src/main/java/com/flow/data/Song.kt
  Mint/Flo/app/src/main/java/com/flow/data/SongDatabase.kt
  Mint/Flo/app/src/main/java/com/flow/ui/HomeFragment.kt
  Mint/Flo/app/src/main/java/com/flow/ui/LockerFragment.kt
  Mint/Flo/app/src/main/java/com/flow/ui/SavedSongFragment.kt
  Mint/Flo/app/src/main/java/com/flow/ui/adapters/AlbumRVAdapter.kt
  Mint/Flo/app/src/main/java/com/flow/ui/adapters/LockerVPAdapter.kt
  Mint/Flo/app/src/main/java/com/flow/ui/adapters/SavedSongRVAdapter.kt
  Mint/Flo/app/src/main/res/layout/fragment_locker.xml
  Mint/Flo/app/src/main/res/layout/item_album.xml
  Mint/Flo/app/src/main/res/layout/item_song.xml
Labels: refactor, feat

#30 6주차미션_릴리
  .idea/workspace.xml
  Lily/Week4/app/src/main/java/com/chrome/umcflo/HomeFragment.kt
  Lily/Week4/app/src/main/java/com/chrome/umcflo/LockerAlbumRVAdapter.kt
  Lily/Week4/app/src/main/java/com/chrome/umcflo/SavedSongFragment.kt
  Lily/Week4/app/src/main/res/layout/recylerview_item.xml
Labels: style, feat

#32 7주차미션_민트
  Mint/Flo/app/src/main/java/com/flow/MainActivity.kt
  Mint/Flo/app/src/main/java/com/flow/NetworkModule.kt
  Mint/Flo/app/src/main/java/com/flow/SongActivity.kt
  Mint/Flo/app/src/main/java/com/flow/SongService.kt
  Mint/Flo/app/src/main/java/com/flow/data/LookView.kt
  Mint/Flo/app/src/main/java/com/flow/data/SongDao.kt
  Mint/Flo/app/src/main/java/com/flow/data/SongDatabase.kt
  Mint/Flo/app/src/main/java/com/flow/data/SongResponse.kt
  Mint/Flo/app/src/main/java/com/flow/data/SongRetrofitInterfaces.kt
  Mint/Flo/app/src/main/java/com/flow/data/User.kt
  Mint/Flo/app/src/main/java/com/flow/data/UserDao.kt
  Mint/Flo/app/src/main/java/com/flow/ui/HomeFragment.kt
  Mint/Flo/app/src/main/java/com/flow/ui/LockFragment.kt
  Mint/Flo/app/src/main/java/com/flow/ui/LockerFragment.kt
  Mint/Flo/app/src/main/java/com/flow/ui/LookFragment.kt
  Mint/Flo/app/src/main/java/com/flow/ui/SavedSongFragment.kt
  Mint/Flo/app/src/main/java/com/flow/ui/adapters/BannerVPAdapter.kt
  Mint/Flo/app/src/main/java/com/flow/ui/adapters/FileRVAdaper.kt
  Mint/Flo/app/src/main/java/com/flow/ui/adapters/SavedSongRVAdapter.kt
  Mint/Flo/app/src/main/java/com/flow/ui/adapters/SongRVAdapter.kt
  Mint/Flo/app/src/main/res/drawable/bg_toast.xml
  Mint/Flo/app/src/main/res/drawable/ic_delete.jpg
  Mint/Flo/app/src/main/res/layout/custom_toast.xml
  Mint/Flo/app/src/main/res/layout/fragment_locker.xml
  Mint/Flo/app/src/main/res/layout/fragment_look.xml
  Mint/Flo/app/src/main/res/values/colors.xml
Labels: refactor, style, feat

#35 8주차미션_릴리
  .idea/workspace.xml
  Lily/Week7/.idea/gradle.xml
  Lily/Week7/.idea/misc.xml
  Lily/Week7/app/src/main/java/com/example/week7/AlbumFragment.kt
  Lily/Week7/app/src/main/java/com/example/week7/Authservice.kt
  Lily/Week7/app/src/main/java/com/example/week7/LockerAlbumRVAdapter.kt
  Lily/Week7/app/src/main/java/com/example/week7/LockerFragment.kt
  Lily/Week7/app/src/main/java/com/example/week7/LoginActivity.kt
  Lily/Week7/app/src/main/java/com/example/week7/LoginView.kt
  Lily/Week7/app/src/main/java/com/example/week7/LookFragment.kt
  Lily/Week7/app/src/main/java/com/example/week7/LookView.kt
  Lily/Week7/app/src/main/java/com/example/week7/MainActivity.kt
  Lily/Week7/app/src/main/java/com/example/week7/SavedAlbumFragment.kt
  Lily/Week7/app/src/main/java/com/example/week7/SignUpActivity.kt
  Lily/Week7/app/src/main/java/com/example/week7/SignUpView.kt
  Lily/Week7/app/src/main/java/com/example/week7/SongRVAdapter.kt
  Lily/Week7/app/src/main/java/com/example/week7/SongResponse.kt
  Lily/Week7/app/src/main/java/com/example/week7/SongService.kt
  Lily/Week7/app/src/main/java/com/example/week7/User.kt
  Lily/Week7/app/src/main/java/com/example/week7/UserDao.kt
  Lily/Week7/app/src/main/res/layout/activity_login.xml
  Lily/Week7/app/src/main/res/layout/activity_sign_up.xml
Labels: style, feat
