Repository UMC-CUK-8th/Android, pull requests merged in 2025-03, with the labels that each got.

#7 1주차미션_민트
  Mint/.gitignore
  Mint/.idea/.gitignore
  Mint/.idea/AndroidProjectSystem.xml
  Mint/.idea/deploymentTargetSelector.xml
  Mint/.idea/gradle.xml
  Mint/.idea/inspectionProfiles/Project_Default.xml
  Mint/.idea/kotlinc.xml
  Mint/.idea/migrations.xml
  Mint/.idea/misc.xml
  Mint/.idea/runConfigurations.xml
  Mint/.idea/vcs.xml
  Mint/app/.gitignore
  Mint/app/build.gradle.kts
  Mint/app/proguard-rules.pro
  Mint/app/src/androidTest/java/com/example/mint/ExampleInstrumentedTest.kt
  Mint/app/src/main/AndroidManifest.xml
  Mint/app/src/main/java/com/example/mint/EmotionSelectionActivity.kt
  Mint/app/src/main/java/com/example/mint/MainActivity.kt
  Mint/app/src/main/java/com/example/mint/NextActivity.kt
  Mint/app/src/main/java/com/example/mint/ui/theme/Color.kt
  Mint/app/src/main/java/com/example/mint/ui/theme/Theme.kt
  Mint/app/src/main/java/com/example/mint/ui/theme/Type.kt
  Mint/app/src/main/res/drawable/ic_angry_face.xml
  Mint/app/src/main/res/drawable/ic_anxious_face.xml
  Mint/app/src/main/res/drawable/ic_custom_back.xml
  Mint/app/src/main/res/drawable/ic_excited_face.xml
  Mint/app/src/main/res/drawable/ic_happy_face.xml
  Mint/app/src/main/res/drawable/ic_launcher_background.xml
  Mint/app/src/main/res/drawable/ic_launcher_foreground.xml
  Mint/app/src/main/res/drawable/ic_normal_face.xml
  Mint/app/src/main/res/layout/activity_emotion_selection.xml
  Mint/app/src/main/res/layout/activity_next.xml
  Mint/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Mint/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Mint/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  Mint/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  Mint/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  Mint/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  Mint/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  Mint/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  Mint/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  Mint/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  Mint/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  Mint/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  Mint/app/src/main/res/values/colors.xml
  Mint/app/src/main/res/values/strings.xml
  Mint/app/src/main/res/values/themes.xml
  Mint/app/src/main/res/xml/backup_rules.xml
  Mint/app/src/main/res/xml/data_extraction_rules.xml
  Mint/app/src/test/java/com/example/mint/ExampleUnitTest.kt
  Mint/build.gradle.kts
  Mint/gradle.properties
  Mint/gradle/libs.versions.toml
  Mint/gradle/wrapper/gradle-wrapper.jar
  Mint/gradle/wrapper/gradle-wrapper.properties
  Mint/gradlew
  Mint/gradlew.bat
  Mint/settings.gradle.kts
  README.md
Labels: refactor, style, feat

#4 1주차미션_릴리
  Week1
  week1
Labels: style

#9 Fix/Bazzi
  Bazzi/.idea/deploymentTargetSelector.xml
  Bazzi/.idea/gradle.xml
  Bazzi/.idea/misc.xml
  Bazzi/app/build.gradle.kts
  Bazzi/app/src/androidTest/java/com/example/bazzi/ExampleInstrumentedTest.kt
  Bazzi/app/src/main/java/com/example/bazzi/BlueActivity.kt
  Bazzi/app/src/main/java/com/example/bazzi/MainActivity.kt
  Bazzi/app/src/main/java/com/example/bazzi/YellowActivity.kt
  Bazzi/app/src/main/java/com/example/bazzi/ui/theme/Color.kt
  Bazzi/app/src/main/java/com/example/bazzi/ui/theme/Theme.kt
  Bazzi/app/src/main/java/com/example/bazzi/ui/theme/Type.kt
  Bazzi/app/src/test/java/com/example/bazzi/ExampleUnitTest.kt
  Bazzi/gradle/wrapper/gradle-wrapper.properties
  Bazzi/settings.gradle.kts
Labels: fix, style

#15 2주차미션_민트
  Mint/.idea/compiler.xml
  Mint/.idea/deploymentTargetSelector.xml
  Mint/app/build.gradle.kts
  Mint/app/src/main/AndroidManifest.xml
  Mint/app/src/main/java/com/example/mint/MainActivity.kt
  Mint/app/src/main/java/com/example/mint/SplashActivity.kt
  Mint/app/src/main/java/com/example/mint/ui/theme/Theme.kt
  Mint/app/src/main/java/com/example/mint/week1/EmotionSelectionActivity.kt
  Mint/app/src/main/java/com/example/mint/week1/NextActivity.kt
  Mint/app/src/main/java/com/example/mint/week2/CalendarScreen.kt
  Mint/app/src/main/java/com/example/mint/week2/HomeScreen.kt
  Mint/app/src/main/java/com/example/mint/week2/PencilScreen.kt
  Mint/app/src/main/java/com/example/mint/week2/ProfileScreen.kt
  Mint/app/src/main/java/com/example/mint/week2/ToYouAppActivity.kt
  Mint/app/src/main/java/com/example/mint/week2/VerticalSegmentedPager.kt
  Mint/app/src/main/res/drawable/ic_calendar.xml
  Mint/app/src/main/res/drawable/ic_home.xml
  Mint/app/src/main/res/drawable/ic_mailbox.xml
  Mint/app/src/main/res/drawable/ic_mint_logo.xml
  Mint/app/src/main/res/drawable/ic_pencil.xml
  Mint/app/src/main/res/drawable/ic_profile.xml
  Mint/app/src/main/res/drawable/ic_red_mailbox.xml
  Mint/app/src/main/res/drawable/ic_speech_buddle.xml
  Mint/app/src/main/res/drawable/ic_toyou_logo.xml
  Mint/app/src/main/res/font/gangwon_edu_hyeonok_t.ttf
Labels: style, feat

#13 2주차미션_잭
  .DS_Store
  Jack/Jack_Week2/.idea/.name
  Jack/Jack_Week2/.idea/misc.xml
  Jack/Jack_Week2/.kotlin/errors/errors-1743137800416.log
  Jack/Jack_Week2/.kotlin/errors/errors-1743138131166.log
  Jack/Jack_Week2/.kotlin/errors/errors-1743155602575.log
  Jack/Jack_Week2/app/build.gradle.kts
  Jack/Jack_Week2/app/src/main/AndroidManifest.xml
  Jack/Jack_Week2/app/src/main/java/com/example/week2_jack/MainActivity.kt
  Jack/Jack_Week2/app/src/main/java/com/example/week2_jack/splashActivity.kt
  Jack/Jack_Week2/app/src/main/res/anim/slide_in.xml
  Jack/Jack_Week2/app/src/main/res/anim/slide_out.xml
  Jack/Jack_Week2/app/src/main/res/drawable/images.png
  Jack/Jack_Week2/app/src/main/res/layout/activity_splash.xml
  Jack/Jack_Week2/app/src/main/res/values/themes.xml
Labels: style
